# name: 연습

# on:
#   push:
#     branches: main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 출력하기
#         run: |
#           echo "github actioins"
#           echo $GITHUB_SHA
#           echo $GITHUB_REPOSITORY
#           echo ${{ secrets.USE_NAME }}

# $GITHUB_SHA : 깃허브에서 Commits 누르면 나오는 이름 (ex. fa932d3)

name: 연습

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 확인
        uses: actions/checkout@v3

      - name: Python 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip

      - name: Run python
        run: python src/app.py